apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "custom-wordpress-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "custom-wordpress-chart.labels" . | nindent 8 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "custom-wordpress-chart.selectorLabels" . | nindent 12 }}
  template:
    metadata:
      labels:
        {{- include "custom-wordpress-chart.selectorLabels" . | nindent 14 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.externalDatabase.host }}
            - name: WORDPRESS_DB_PORT
              value: "{{ .Values.externalDatabase.port }}"
            - name: WORDPRESS_DB_USER
              value: {{ .Values.externalDatabase.user }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.externalDatabase.password }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.externalDatabase.database }}
            - name: WORDPRESS_USERNAME
              value: {{ .Values.wordpress.username }}
            - name: WORDPRESS_PASSWORD
              value: {{ .Values.wordpress.password }}
            - name: WORDPRESS_EMAIL
              value: {{ .Values.wordpress.email }}
            - name: WORDPRESS_BLOG_NAME
              value: {{ .Values.wordpress.blogName }}
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            {{- if .Values.persistence.enabled }}
            claimName: {{ include "custom-wordpress-chart.fullname" . }}-pvc
            {{- end }}