apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "custom-wordpress-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "custom-wordpress-chart.selectorLabels" . | nindent 8 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s